### ISSUE TITLE
Bilgi güvenliği için sitenin kapatılması

### ISSUE THREAD

**Issue by frost768** [cihatislamdede/deprem-yardim#14]
Merhaba,
Sitenin hala kullanımda fakat bilgilerin güvenliği için kapatmanız daha uygun gibi geliyor.
Her ne kadar numara çıkarımı için bir şeyler yazmış olsam da bu kötü niyetli kişiler için daha kolay bir yol sunuyor.
İnsanların telefon üzerinden rahatsız edilmesine karşılık önerim sitenin erişime kapatılması ya da en azından bir bilgilendirme bırakılarak listenin gösterilmemesidir.

**Comment by cihatislamdede** [comment]
Merhaba,
Telefon numaraları Twitter gibi platformlarda da paylaşılmış durumda, öyle bir niyeti olan kişilerin önüne geçmek pek mümkün gözükmüyor. Bir kişinin bile işine yarayabileceğini (teyit veya yardım amaçlı) düşündüğümüz için şimdilik açık tutmaya devam ediyoruz. İnşallah olayları atlattıktan sonra tüm verileri temizleyip siteyi deaktif edeceğiz.

Edit: Şu anda sadece güncel olan talepleri gösteriyoruz.
