### ISSUE TITLE
Lojistik Optimizasyonu Projesi ile entegrasyon ve iletişim

### ISSUE THREAD

**Issue by selamikarakas** [cihatislamdede/deprem-yardim#9]
Merhabalar, yardımların ulaşım sürecini optimize etmek için çalışıyoruz ekibimize katılmanız ve projenizi tanıtmanız mümkün olur mu? Haberdar ederseniz sevinirim.

**Comment by cihatislamdede** [comment]
Merhaba, tabii ki yardım etmek isterim. Buraya mail atabilirsiniz chtddgs6@gmail.com @selamikarakas
